### ISSUE TITLE
[Bug] Instant disconnected after Encryption phase when connecting to Server behind Cloudflare

### ISSUE THREAD

**Issue by mokocup** [rikka0w0/wsmc#3]
### Describe the Bug
When you connect to Server behind Cloudflare , instant disconnect after Encrypting phase
### Expected Behavior
Able to connect
### Steps To Reproduce
1. Boot the server
2. Boot the game
3. Connect to server

**Comment by rikka0w0** [comment]
Could you share your Minecraft version, mod env (forge/fabric), and installed mod list?

**Comment by rikka0w0** [comment]
Should be fixed in #1
